### ISSUE TITLE
It is working for Skype, but not for other application.

### ISSUE THREAD

**Issue by BakingBrains** [razier/TeddVirtualNetworkCamClient#1]
Any suggestions here?

**Comment by razier** [comment]
Do you mean you manage to send frames to skype and skype is able to show the frame?

What other application and the version of the application you are trying to use it with?

There's actually 3 type of "virtual webcam"
1. Kernel based driver
2. DirectShow source filter (This is the one Tedd did)
3.  Media Foundation

Most old apps supports DirectShow filter, however newer apps are either using Media Foundation or fall back to Kernel based driver; which might be one of the possibility on why the camera does not appear / does not seem to work on some applications.

**Comment by BakingBrains** [comment]
@razier I am using the Tedd virtual cam. It is able to send the frames and skype is able to show, but for Zoom, WebX, etc it's not at all working. 

Zoom Version = 5.9.1
WebX Version = 42.1

Thank you

**Comment by razier** [comment]
@BakingBrains I just tested with Cisco Webex version 42.1.4.22, seems to be working on my end.

Did you install both 32bit and 62bit of Tedd.VirtualNetworkCam?
https://github.com/tedd/Tedd.VirtualNetworkCam#note-on-32-bit64-bit

**Comment by BakingBrains** [comment]
@razier I tried with 32 bit and 64 bit. Still it was not working

**Comment by BakingBrains** [comment]
@razier Yes, I rebuilt and installed it again it was working for webX, but all of the sudden I am unable to send the frames. The TCP port is running, but when I run the code, it throws this error ```Unable to Connect :  [WinError 10061] No connection could be made because the target machine actively refused it```.

**Comment by razier** [comment]
@BakingBrains It might be that an old instance of Tedd.VirtualNetworkCam is still holding onto the port 9090, try checking %temp%\Tedd.VirtualNetworkCam.log or even restarting the entire computer then start Webex and select the webcam.

If it still fails, try to test using a command prompt via telnet localhost 9090

**Comment by razier** [comment]
Close due to inactivity, do raise a new issue if you still have problem running this.
